apiVersion: v1
kind: Service
metadata:
  name: kratos
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kratos
  ports:
    - name: public
      port: 80
      targetPort: 4433
      protocol: TCP
    - name: admin
      port: 4434
      targetPort: 4434
      protocol: TCP
