apiVersion: v1
kind: Service
metadata:
  name: mail-slurper
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mail-slurper
  ports:
    - name: a
      port: 4436
      targetPort: 4436
      protocol: TCP
    - name: b
      port: 4437
      targetPort: 4437
      protocol: TCP
