# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: drs
# spec:
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: drs
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/name: drs
#     spec:
#       containers:
#         - image: 282236276875.dkr.ecr.us-east-2.amazonaws.com/ga4gh-starter-kit-drs:xxxxxx
#           name: drs
#           command: ["java", "-jar", "ga4gh-starter-kit-drs.jar", "-c", "/etc/config.yml" ]
#           volumeMounts:
#             - name: drs-config
#               mountPath: /etc/config.yml
#               subPath: config.yml
#               readOnly: true
#           ports:
#             - containerPort: 4500
#             - containerPort: 4501
#       imagePullSecrets:
#         - name: ecr-registry-key
#       volumes:
#         - name: drs-config
#           secret:
#             secretName: drs-config
