# apiVersion: v1
# kind: Service
# metadata:
#   name: drs
# spec:
#   type: NodePort
#   selector:
#     app.kubernetes.io/name: drs
#   ports:
#     - name: a
#       port: 4500
#       targetPort: 4500
#       protocol: TCP
#     - name: b
#       port: 4501
#       targetPort: 4501
#       protocol: TCP
