apiVersion: batch/v1
kind: Job
metadata:
  name: hydra-db-migration
spec:
  template:
    spec:
      volumes:
        - name: hydra-config-map
          configMap:
            name: hydra-config-map
      containers:
        - name: hydra-db-migration
          image: oryd/hydra:v1.11.7
          volumeMounts:
            - name: hydra-config-map
              mountPath: /etc/config
              readOnly: true
          command: ["hydra", "-c", "/etc/config/hydra.yaml", "migrate", "sql", "-e", "--yes"]
          env:
            - name: DSN
              value: postgres://hydra:secret@host.docker.internal:5432/hydra?sslmode=disable
      restartPolicy: Never
  backoffLimit: 4