apiVersion: apps/v1
kind: Deployment
metadata:
  name: passport-ui-node
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: passport-ui-node
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: passport-ui-node
    spec:
      containers:
        - image: ga4gh/ga4gh-starter-kit-passport-ui-node:0.0.2
          name: passport-ui-node
          ports:
            - containerPort: 4455
          env:
            - name: KRATOS_PUBLIC_URL
              value: http://kratos:80/
            - name: KRATOS_ADMIN_URL
              value: http://kratos:4434/
            - name: KRATOS_BROWSER_URL
              value: http://{{ .Values.ga4gh.referenceCloud.baseURL }}/
            - name: HYDRA_ADMIN_URL
              value: http://hydra:4445/
            - name: PASSPORT_BROKER_PUBLIC_URL
              value: http:/passport-broker:4500/ga4gh/passport/v1/
            - name: PASSPORT_BROKER_ADMIN_URL
              value: http://passport-broker:4501/admin/ga4gh/passport/v1/
            - name: PORT
              value: "4455"
            - name: SECURITY_MODE
              value: ""
