apiVersion: v1
kind: Service
metadata:
  name: passport-ui-node
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: passport-ui-node
  ports:
    - port: 4455
      targetPort: 4455
      protocol: TCP
