apiVersion: batch/v1
kind: Job
metadata:
  name: refcloud-api-db-migration
spec:
  template:
    spec:
      containers:
        - name: refcloud-api-db-migration
          image: 282236276875.dkr.ecr.us-east-2.amazonaws.com/refcloud-api-liquibase:v0.3.2-99-g5f94342
          env:
            - name: PSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: common-db-info
                  key: host
            - name: PSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: common-db-info
                  key: port
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: refcloud-api-db-credentials
                  key: username
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: refcloud-api-db-credentials
                  key: password
            - name: LIQUIBASE_COMMAND_URL
              value: jdbc:postgresql://$(PSQL_HOST):$(PSQL_PORT)/$(LIQUIBASE_COMMAND_USERNAME)
      restartPolicy: Never
      imagePullSecrets:
        - name: ecr-registry-key
  backoffLimit: 4
