apiVersion: v1
kind: Service
metadata:
  name: refcloud-ui
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: refcloud-ui
  ports:
    - name: public
      port: 3000
      targetPort: 3000
      protocol: TCP
