apiVersion: apps/v1
kind: Deployment
metadata:
  name: passport-ui-hydra
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: passport-ui-hydra
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: passport-ui-hydra
    spec:
      containers:
        - image: oryd/hydra-login-consent-node:v1.11.8
          imagePullPolicy: Always
          name: passport-ui-hydra
          ports:
            - containerPort: 3000
              hostPort: 3000
          env:
            - name: HYDRA_ADMIN_URL
              value: http://hydra:4445/
            - name: KRATOS_PUBLIC_URL
              value: http://kratos:4433/
            - name: KRATOS_ADMIN_URL
              value: http://kratos:4434/
