apiVersion: batch/v1
kind: Job
metadata:
  name: ory-kratos-db-migration
spec:
  template:
    spec:
      volumes:
        - name: ory-kratos-config-map
          configMap:
            name: ory-kratos-config-map
      containers:
        - name: ory-kratos-db-migration
          image: oryd/kratos:v0.9.0-alpha.2
          volumeMounts:
            - name: ory-kratos-config-map
              mountPath: /etc/config
              readOnly: true
          command: ["kratos", "-c", "/etc/config/kratos.yaml", "migrate", "sql", "-e", "--yes"]
          env:
            - name: DSN
              value: postgres://kratos:kratos@host.docker.internal:5432/kratos?sslmode=disable
      restartPolicy: Never
  backoffLimit: 4